// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StadProtoModel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stad.Model {

  /// <summary>Holder for reflection information generated from StadProtoModel.proto</summary>
  public static partial class StadProtoModelReflection {

    #region Descriptor
    /// <summary>File descriptor for StadProtoModel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StadProtoModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRTdGFkUHJvdG9Nb2RlbC5wcm90bxIKU3RhZC5Nb2RlbCI7Cg1SZWdpc3Ry",
            "eVByb3RvEioKCERhdGFTZXRzGAEgAygLMhguU3RhZC5Nb2RlbC5EYXRhU2V0",
            "UHJvdG8ifgoMRGF0YVNldFByb3RvEgwKBE5hbWUYASABKAkSLgoKTGlzdE1v",
            "ZGVscxgCIAMoCzIaLlN0YWQuTW9kZWwuU3RhZE1vZGVsUHJvdG8SMAoMU2lu",
            "Z2xlTW9kZWxzGAMgAygLMhouU3RhZC5Nb2RlbC5TdGFkTW9kZWxQcm90byKd",
            "AQoOU3RhZE1vZGVsUHJvdG8SDAoEVHlwZRgBIAEoCRIQCghUeXBlQ29kZRgC",
            "IAEoBRI3Cg5Bbm5vdGF0aW9uaW5mbxgDIAEoCzIfLlN0YWQuTW9kZWwuQW5u",
            "b3RhdGlvbkluZm9Qcm90bxIyCgdNZW1iZXJzGAQgAygLMiEuU3RhZC5Nb2Rl",
            "bC5NZW1iZXJEZWZpbml0aW9uUHJvdG8iSwoTQW5ub3RhdGlvbkluZm9Qcm90",
            "bxI0CgtBbm5vdGF0aW9ucxgBIAMoCzIfLlN0YWQuTW9kZWwuU3RhZEFubm90",
            "YXRpb25Qcm90byIjChNTdGFkQW5ub3RhdGlvblByb3RvEgwKBEpzb24YASAB",
            "KAkikgEKFU1lbWJlckRlZmluaXRpb25Qcm90bxIMCgRUeXBlGAEgASgJEgwK",
            "BE5hbWUYAiABKAkSJAoES2luZBgDIAEoDjIWLlN0YWQuTW9kZWwuTWVtYmVy",
            "S2luZBI3Cg5Bbm5vdGF0aW9uSW5mbxgEIAEoCzIfLlN0YWQuTW9kZWwuQW5u",
            "b3RhdGlvbkluZm9Qcm90bypVCgpNZW1iZXJLaW5kEhgKFE1lbWJlcktpbmRf",
            "VW5kZWZpbmVkEAASFAoQTWVtYmVyS2luZF9GaWVsZBABEhcKE01lbWJlcktp",
            "bmRfUHJvcGVydHkQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Stad.Model.MemberKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.RegistryProto), global::Stad.Model.RegistryProto.Parser, new[]{ "DataSets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.DataSetProto), global::Stad.Model.DataSetProto.Parser, new[]{ "Name", "ListModels", "SingleModels" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.StadModelProto), global::Stad.Model.StadModelProto.Parser, new[]{ "Type", "TypeCode", "Annotationinfo", "Members" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.AnnotationInfoProto), global::Stad.Model.AnnotationInfoProto.Parser, new[]{ "Annotations" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.StadAnnotationProto), global::Stad.Model.StadAnnotationProto.Parser, new[]{ "Json" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stad.Model.MemberDefinitionProto), global::Stad.Model.MemberDefinitionProto.Parser, new[]{ "Type", "Name", "Kind", "AnnotationInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  //////////////////////// 변환 없이 사용되는 것들 ///////////////////////
  /// </summary>
  public enum MemberKind {
    [pbr::OriginalName("MemberKind_Undefined")] Undefined = 0,
    [pbr::OriginalName("MemberKind_Field")] Field = 1,
    [pbr::OriginalName("MemberKind_Property")] Property = 2,
  }

  #endregion

  #region Messages
  public sealed partial class RegistryProto : pb::IMessage<RegistryProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegistryProto> _parser = new pb::MessageParser<RegistryProto>(() => new RegistryProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegistryProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistryProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistryProto(RegistryProto other) : this() {
      dataSets_ = other.dataSets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistryProto Clone() {
      return new RegistryProto(this);
    }

    /// <summary>Field number for the "DataSets" field.</summary>
    public const int DataSetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Stad.Model.DataSetProto> _repeated_dataSets_codec
        = pb::FieldCodec.ForMessage(10, global::Stad.Model.DataSetProto.Parser);
    private readonly pbc::RepeatedField<global::Stad.Model.DataSetProto> dataSets_ = new pbc::RepeatedField<global::Stad.Model.DataSetProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Stad.Model.DataSetProto> DataSets {
      get { return dataSets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegistryProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegistryProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dataSets_.Equals(other.dataSets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dataSets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dataSets_.WriteTo(output, _repeated_dataSets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dataSets_.WriteTo(ref output, _repeated_dataSets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dataSets_.CalculateSize(_repeated_dataSets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegistryProto other) {
      if (other == null) {
        return;
      }
      dataSets_.Add(other.dataSets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dataSets_.AddEntriesFrom(input, _repeated_dataSets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dataSets_.AddEntriesFrom(ref input, _repeated_dataSets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DataSetProto : pb::IMessage<DataSetProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataSetProto> _parser = new pb::MessageParser<DataSetProto>(() => new DataSetProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataSetProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSetProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSetProto(DataSetProto other) : this() {
      name_ = other.name_;
      listModels_ = other.listModels_.Clone();
      singleModels_ = other.singleModels_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataSetProto Clone() {
      return new DataSetProto(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ListModels" field.</summary>
    public const int ListModelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Stad.Model.StadModelProto> _repeated_listModels_codec
        = pb::FieldCodec.ForMessage(18, global::Stad.Model.StadModelProto.Parser);
    private readonly pbc::RepeatedField<global::Stad.Model.StadModelProto> listModels_ = new pbc::RepeatedField<global::Stad.Model.StadModelProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Stad.Model.StadModelProto> ListModels {
      get { return listModels_; }
    }

    /// <summary>Field number for the "SingleModels" field.</summary>
    public const int SingleModelsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Stad.Model.StadModelProto> _repeated_singleModels_codec
        = pb::FieldCodec.ForMessage(26, global::Stad.Model.StadModelProto.Parser);
    private readonly pbc::RepeatedField<global::Stad.Model.StadModelProto> singleModels_ = new pbc::RepeatedField<global::Stad.Model.StadModelProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Stad.Model.StadModelProto> SingleModels {
      get { return singleModels_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataSetProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataSetProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!listModels_.Equals(other.listModels_)) return false;
      if(!singleModels_.Equals(other.singleModels_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= listModels_.GetHashCode();
      hash ^= singleModels_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      listModels_.WriteTo(output, _repeated_listModels_codec);
      singleModels_.WriteTo(output, _repeated_singleModels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      listModels_.WriteTo(ref output, _repeated_listModels_codec);
      singleModels_.WriteTo(ref output, _repeated_singleModels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += listModels_.CalculateSize(_repeated_listModels_codec);
      size += singleModels_.CalculateSize(_repeated_singleModels_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataSetProto other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      listModels_.Add(other.listModels_);
      singleModels_.Add(other.singleModels_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            listModels_.AddEntriesFrom(input, _repeated_listModels_codec);
            break;
          }
          case 26: {
            singleModels_.AddEntriesFrom(input, _repeated_singleModels_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            listModels_.AddEntriesFrom(ref input, _repeated_listModels_codec);
            break;
          }
          case 26: {
            singleModels_.AddEntriesFrom(ref input, _repeated_singleModels_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StadModelProto : pb::IMessage<StadModelProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StadModelProto> _parser = new pb::MessageParser<StadModelProto>(() => new StadModelProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StadModelProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadModelProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadModelProto(StadModelProto other) : this() {
      type_ = other.type_;
      typeCode_ = other.typeCode_;
      annotationinfo_ = other.annotationinfo_ != null ? other.annotationinfo_.Clone() : null;
      members_ = other.members_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadModelProto Clone() {
      return new StadModelProto(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TypeCode" field.</summary>
    public const int TypeCodeFieldNumber = 2;
    private int typeCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TypeCode {
      get { return typeCode_; }
      set {
        typeCode_ = value;
      }
    }

    /// <summary>Field number for the "Annotationinfo" field.</summary>
    public const int AnnotationinfoFieldNumber = 3;
    private global::Stad.Model.AnnotationInfoProto annotationinfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Stad.Model.AnnotationInfoProto Annotationinfo {
      get { return annotationinfo_; }
      set {
        annotationinfo_ = value;
      }
    }

    /// <summary>Field number for the "Members" field.</summary>
    public const int MembersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Stad.Model.MemberDefinitionProto> _repeated_members_codec
        = pb::FieldCodec.ForMessage(34, global::Stad.Model.MemberDefinitionProto.Parser);
    private readonly pbc::RepeatedField<global::Stad.Model.MemberDefinitionProto> members_ = new pbc::RepeatedField<global::Stad.Model.MemberDefinitionProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Stad.Model.MemberDefinitionProto> Members {
      get { return members_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StadModelProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StadModelProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (TypeCode != other.TypeCode) return false;
      if (!object.Equals(Annotationinfo, other.Annotationinfo)) return false;
      if(!members_.Equals(other.members_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (TypeCode != 0) hash ^= TypeCode.GetHashCode();
      if (annotationinfo_ != null) hash ^= Annotationinfo.GetHashCode();
      hash ^= members_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (TypeCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TypeCode);
      }
      if (annotationinfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Annotationinfo);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (TypeCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TypeCode);
      }
      if (annotationinfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Annotationinfo);
      }
      members_.WriteTo(ref output, _repeated_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (TypeCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeCode);
      }
      if (annotationinfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Annotationinfo);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StadModelProto other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.TypeCode != 0) {
        TypeCode = other.TypeCode;
      }
      if (other.annotationinfo_ != null) {
        if (annotationinfo_ == null) {
          Annotationinfo = new global::Stad.Model.AnnotationInfoProto();
        }
        Annotationinfo.MergeFrom(other.Annotationinfo);
      }
      members_.Add(other.members_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 16: {
            TypeCode = input.ReadInt32();
            break;
          }
          case 26: {
            if (annotationinfo_ == null) {
              Annotationinfo = new global::Stad.Model.AnnotationInfoProto();
            }
            input.ReadMessage(Annotationinfo);
            break;
          }
          case 34: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 16: {
            TypeCode = input.ReadInt32();
            break;
          }
          case 26: {
            if (annotationinfo_ == null) {
              Annotationinfo = new global::Stad.Model.AnnotationInfoProto();
            }
            input.ReadMessage(Annotationinfo);
            break;
          }
          case 34: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AnnotationInfoProto : pb::IMessage<AnnotationInfoProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnnotationInfoProto> _parser = new pb::MessageParser<AnnotationInfoProto>(() => new AnnotationInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnnotationInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnotationInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnotationInfoProto(AnnotationInfoProto other) : this() {
      annotations_ = other.annotations_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnnotationInfoProto Clone() {
      return new AnnotationInfoProto(this);
    }

    /// <summary>Field number for the "Annotations" field.</summary>
    public const int AnnotationsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Stad.Model.StadAnnotationProto> _repeated_annotations_codec
        = pb::FieldCodec.ForMessage(10, global::Stad.Model.StadAnnotationProto.Parser);
    private readonly pbc::RepeatedField<global::Stad.Model.StadAnnotationProto> annotations_ = new pbc::RepeatedField<global::Stad.Model.StadAnnotationProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Stad.Model.StadAnnotationProto> Annotations {
      get { return annotations_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnnotationInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnnotationInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!annotations_.Equals(other.annotations_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= annotations_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      annotations_.WriteTo(output, _repeated_annotations_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      annotations_.WriteTo(ref output, _repeated_annotations_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += annotations_.CalculateSize(_repeated_annotations_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnnotationInfoProto other) {
      if (other == null) {
        return;
      }
      annotations_.Add(other.annotations_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            annotations_.AddEntriesFrom(input, _repeated_annotations_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            annotations_.AddEntriesFrom(ref input, _repeated_annotations_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StadAnnotationProto : pb::IMessage<StadAnnotationProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StadAnnotationProto> _parser = new pb::MessageParser<StadAnnotationProto>(() => new StadAnnotationProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StadAnnotationProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadAnnotationProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadAnnotationProto(StadAnnotationProto other) : this() {
      json_ = other.json_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StadAnnotationProto Clone() {
      return new StadAnnotationProto(this);
    }

    /// <summary>Field number for the "Json" field.</summary>
    public const int JsonFieldNumber = 1;
    private string json_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Json {
      get { return json_; }
      set {
        json_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StadAnnotationProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StadAnnotationProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Json != other.Json) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Json.Length != 0) hash ^= Json.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Json.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Json);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Json.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Json);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Json.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Json);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StadAnnotationProto other) {
      if (other == null) {
        return;
      }
      if (other.Json.Length != 0) {
        Json = other.Json;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Json = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Json = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MemberDefinitionProto : pb::IMessage<MemberDefinitionProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MemberDefinitionProto> _parser = new pb::MessageParser<MemberDefinitionProto>(() => new MemberDefinitionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemberDefinitionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stad.Model.StadProtoModelReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberDefinitionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberDefinitionProto(MemberDefinitionProto other) : this() {
      type_ = other.type_;
      name_ = other.name_;
      kind_ = other.kind_;
      annotationInfo_ = other.annotationInfo_ != null ? other.annotationInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemberDefinitionProto Clone() {
      return new MemberDefinitionProto(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Kind" field.</summary>
    public const int KindFieldNumber = 3;
    private global::Stad.Model.MemberKind kind_ = global::Stad.Model.MemberKind.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Stad.Model.MemberKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "AnnotationInfo" field.</summary>
    public const int AnnotationInfoFieldNumber = 4;
    private global::Stad.Model.AnnotationInfoProto annotationInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Stad.Model.AnnotationInfoProto AnnotationInfo {
      get { return annotationInfo_; }
      set {
        annotationInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemberDefinitionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemberDefinitionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Kind != other.Kind) return false;
      if (!object.Equals(AnnotationInfo, other.AnnotationInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Kind != global::Stad.Model.MemberKind.Undefined) hash ^= Kind.GetHashCode();
      if (annotationInfo_ != null) hash ^= AnnotationInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Stad.Model.MemberKind.Undefined) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (annotationInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AnnotationInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Kind != global::Stad.Model.MemberKind.Undefined) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (annotationInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AnnotationInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Kind != global::Stad.Model.MemberKind.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (annotationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnnotationInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemberDefinitionProto other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Kind != global::Stad.Model.MemberKind.Undefined) {
        Kind = other.Kind;
      }
      if (other.annotationInfo_ != null) {
        if (annotationInfo_ == null) {
          AnnotationInfo = new global::Stad.Model.AnnotationInfoProto();
        }
        AnnotationInfo.MergeFrom(other.AnnotationInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Stad.Model.MemberKind) input.ReadEnum();
            break;
          }
          case 34: {
            if (annotationInfo_ == null) {
              AnnotationInfo = new global::Stad.Model.AnnotationInfoProto();
            }
            input.ReadMessage(AnnotationInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Kind = (global::Stad.Model.MemberKind) input.ReadEnum();
            break;
          }
          case 34: {
            if (annotationInfo_ == null) {
              AnnotationInfo = new global::Stad.Model.AnnotationInfoProto();
            }
            input.ReadMessage(AnnotationInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
